[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change header'"
excluded-patches = "'Open links externally' 'Spoof device dimensions' 'Disable zoom haptics' 'GmsCore support' 'Enable debugging' 'Announcements' 'Always repeat' 'Custom player overlay opacity' 'Hide cast button' 'Return YouTube Dislike' 'Enable tablet layout' 'Wide searchbar' 'Disable rolling number animations' 'Hide timestamp' 'Copy video URL' 'Disable precise seeking gesture' 'Swipe controls'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'GmsCore support'"
